apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-devops-deployment
spec:
  selector:
    matchLabels:
      app: santa  # Correspond maintenant aux labels du template
  replicas: 2
  template:
    metadata:
      labels:
        app: santa  # Label correspondant au selector
    spec:
      containers:
        - name: santa
          image: houssembwfi/tpfoyer-devops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080  # Le port sur lequel le conteneur écoute
---
apiVersion: v1
kind: Service
metadata:
  name: santa-ssvc
spec:
  selector:
    app: santa
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081
  type: LoadBalancer
