apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_DATABASE
              value: db
          ports:
            - containerPort: 3306
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpfoyer-devops-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: santa
  template:
    metadata:
      labels:
        app: santa
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
        - name: santa-backend
          image: houssembwfi/tpfoyer-devops:latest
          ports:
            - containerPort: 8089
          env:
            - name: DB_URL
              value: jdbc:mysql://mysql-service:3306/db?createDatabaseIfNotExist=true
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root_password
            - name: SERVER_PORT
              value: "8089"
            - name: SERVER_CONTEXT_PATH
              value: /tpfoyer
          readinessProbe:
            httpGet:
              path: /tpfoyer/actuator/health
              port: 8089
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: santa-ssvc
spec:
  selector:
    app: santa
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer
