version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password  # Remplacez par un mot de passe sécurisé
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'  
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  spring-app:
    image: houssembwfi/tpfoyer-devops:latest
    ports:
      - "8090:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root # Ajoutez cette ligne si vous utilisez un mot de passe
