version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD:  
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  
      MYSQL_DATABASE: devops
    ports:
      - "3306:3306"

  spring-app:
    image: ghaithameur/5artic3-g5-devops:latest
    ports:
      - "8090:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
