version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"

  spring-app:
    image: houssembwfi/tpfoyer-devops:latest
    ports:
      - "8090:8089"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
     
