apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: houcem-mysql-deployment
  annotations:
    description: "this is a deployment for mysql database instance"
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql-abc
    app.kubernetes.io/version: "8.0"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: houcem-solution
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: houcem-mysql
  template:
    metadata:
      labels:
        app: houcem-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: houcem-mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root_password
            - name: MYSQL_DATABASE
              value: db
          ports:
            - containerPort: 3306
  #         volumeMounts:
  #           - name: houcem-vct
  #             mountPath: /var/lib/mysql          
  # volumeClaimTemplates:
  # - metadata:
  #     name: houcem-vct
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     #storageClassName: "gp2" jareb ken tfassa5ha yet3adelek wela le  (gp2->mte3 aws moch Azure)
  #     resources:
  #       requests:
  #         storage: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: houcem-mysql-service
  labels:
    app.kubernetes.io/name: houcem-mysql-service
    app.kubernetes.io/instance: houcem-mysql-service-abc
    app: houcem-mysql-service
spec:
  ports:
    - port: 3306
  clusterIP: None 
  selector:
    app: houcem-mysql
